@baseUrl = http://localhost:5067
@accessToken = replace_with_jwt_after_login
@merchantId = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa

### Health
GET {{baseUrl}}/api/health
Accept: application/json

###
### Database ready
GET {{baseUrl}}/health/ready
Accept: application/json

###
### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@payscope.local",
  "password": "Admin123!"
}

###
### Current user
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{accessToken}}
Accept: application/json

###
### Access profile
GET {{baseUrl}}/api/auth/access
Authorization: Bearer {{accessToken}}
Accept: application/json

###
### Admin check
GET {{baseUrl}}/api/auth/admin-check
Authorization: Bearer {{accessToken}}
Accept: application/json

###
### Analyst check
GET {{baseUrl}}/api/auth/analyst-check
Authorization: Bearer {{accessToken}}
Accept: application/json

###
### List merchants
GET {{baseUrl}}/api/merchants?page=1&pageSize=10
Authorization: Bearer {{accessToken}}
Accept: application/json

###
### Search merchants
GET {{baseUrl}}/api/merchants?page=1&pageSize=10&search=cafe&isActive=true
Authorization: Bearer {{accessToken}}
Accept: application/json

###
### Merchant detail
GET {{baseUrl}}/api/merchants/{{merchantId}}
Authorization: Bearer {{accessToken}}
Accept: application/json

###
### Create merchant
POST {{baseUrl}}/api/merchants
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "merchantCode": "MCH-DEMO-99",
  "name": "Demo Merchant",
  "category": "Retail",
  "isActive": true
}

###
### Update merchant
PUT {{baseUrl}}/api/merchants/{{merchantId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "PayScope Market Istanbul Updated",
  "category": "Grocery"
}

###
### Activate merchant
POST {{baseUrl}}/api/merchants/{{merchantId}}/activate
Authorization: Bearer {{accessToken}}
Accept: application/json

###
### Deactivate merchant
POST {{baseUrl}}/api/merchants/{{merchantId}}/deactivate
Authorization: Bearer {{accessToken}}
Accept: application/json
